# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
development:
  FITBIT_CLIENT_ID: "22CNGT"
  FITBIT_CLIENT_SECRET: "8bee3a2c55b20be45738ad3d2e7081d9"

CLOUDINARY_URL: "cloudinary://974658846872547:00r496t7K5sPM4iplg3BUAniut0@henry0203"

STRIPE_PUBLISHABLE_KEY: "pk_test_WELrtEaONoXX35jUJjOIH6T7"
STRIPE_SECRET_KEY: "sk_test_aslCq8KU1t0q5JSGnNxegNDP"
